[package]
name = "minimal"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
edition = "2018"

[dependencies]
plaster = { path = "../.." }
log = "0.4"
console_log = "0.1"
wasm-bindgen = "0.2"
